### ISSUE TITLE
SocketPipe assigns read pipe and write pipe after kicking off the thread

### ISSUE THREAD

**Issue by davidfowl** [thomhurst/A-sync-RedisClient#3]
This is a race condition that may result in a null ref (it happened to me). The fix is simple though. 

https://github.com/thomhurst/A-sync-RedisClient/blob/068a87f548dcb668ec6864d296ff4c74bc3d158a/TomLonghurst.RedisClient/Pipes/SocketPipe.cs#L51-L65

**Comment by thomhurst** [comment]
Thanks David. Sorted!
